 
os:
  - linux

language: generic

services:
  - docker
env:
  global:
    - REPO_NAME=pyspline
    - DOCKER_WORKING_DIR=/home/mdolabuser/repos/$REPO_NAME
    - DOCKER_MOUNT_DIR=/home/mdolabuser/travis/$REPO_NAME
  jobs:
    # - DOCKER_TAG=c7-gcc-ompi-py3-latest
    - DOCKER_TAG=c7-intel-impi-py3-latest
    - DOCKER_TAG=u18-gcc-ompi-py2-stable
    - DOCKER_TAG=u18-gcc-ompi-py3-latest
    - DOCKER_TAG=u18-gcc-ompi-py3-stable
    - DOCKER_TAG=u20-gcc-ompi-py3-latest
    - DOCKER_TAG=u20-gcc-ompi-py3-stable

before_install:
  - docker pull mdolab/public:$DOCKER_TAG
  # run Docker, key is we mount the current Travis directory into Docker to access content of repo
  - docker run -t -d 
        --name app
        --mount "type=bind,src=$(pwd),target=$DOCKER_MOUNT_DIR"
        mdolab/public:$DOCKER_TAG
        /bin/bash

install:
  # We thrown away the existing repo in Docker, and copy the new one in-place
  - docker exec -it app /bin/bash -c "rm -rf $DOCKER_WORKING_DIR && cp -r $DOCKER_MOUNT_DIR $DOCKER_WORKING_DIR"
  - if [[ "$DOCKER_TAG" == "py2"* ]]; then
      docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR && cp config/defaults/config.LINUX_GFORTRAN.mk config/config.mk && sed -i 's/python3-config/python-config/g' config/config.mk && make";
    else
      docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR && cp config/defaults/config.LINUX_GFORTRAN.mk config/config.mk && make";
    fi

  - docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR && pip install ."

script:
  # We need to source the mdolab bashrc before running anything
  - docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR && testflo . -v"

after_script:
  - docker rm -f app
